# Generated by Django 5.1.2 on 2024-10-29 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DistanceCalculation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_address', models.CharField(max_length=255)),
                ('end_address', models.CharField(max_length=255)),
                ('distance_km', models.DecimalField(decimal_places=2, max_digits=10)),
                ('calculation_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
